```{r imports} 
library(DESeq2)
library(data.table)
library(readxl)
library(limma)
library(ggplot2)
library(ggrepel)
library(pheatmap)
library(umap)
library(apeglm)
library(EnhancedVolcano)
library(magrittr)
```

```{r read counts}
counts <- fread("../../data/novogene_raw_gene_count.xls") %>% as.data.frame

rownames(counts) <- counts$gene_id

# only AAVS1 and SATB1 cols
counts <- counts[c(2:3, 6:7, 10:11, 14:15, 18:19, 22:23)]
counts

# generate metadata for DESeq2
meta_data <- data.frame( index = colnames(counts) )
rownames(meta_data) <- meta_data$index

meta_data$condition <- as.factor(substr(meta_data$index, 6, 6))
meta_data$batch <- as.factor(substr(meta_data$index, 8, 9)) 
meta_data$cell <- as.factor(substr(meta_data$index, 1, 4))

meta_data$index <- NULL

meta_data
```


```{r DESeq2}
dds <- DESeqDataSetFromMatrix(countData = counts,
                              colData = meta_data,
                              design = ~ batch + cell + condition)
dds <- DESeq(dds)
```

https://support.bioconductor.org/p/101613/
https://support.bioconductor.org/p/76099/
```{r PCA}
vsd <- vst(dds)

# without batch correction
plotPCA(vsd, intgroup = c("condition"))

mm <- model.matrix(~condition + cell, colData(vsd))

# limma batch correct
assay(vsd) <- limma::removeBatchEffect(assay(vsd), vsd$batch, design=mm)
pca_data <- plotPCA(vsd, intgroup = c("condition", "cell"), returnData=TRUE)
pca_data

percentVar <- round(100 * attr(pca_data, "percentVar"))
percentVar

ggplot(pca_data, aes(x=PC1, y=PC2, color=condition, shape=cell, label=name)) +
  geom_point(size=2) +
  labs(x=paste0("PC1: ", percentVar[1], "% variance"), y=paste0("PC2: ", percentVar[2], "% variance")) +
  geom_text_repel(size=3.5)

ggsave("../../results/pca/rna_teff_treg_PCA.pdf")
```

```{r save batch corrected and normalized counts}
vsd <- vst(dds)

mm <- model.matrix(~condition + cell, colData(vsd))

limma_counts <- limma::removeBatchEffect(assay(vsd), vsd$batch, design=mm)

write.csv(limma_counts, "../../data/novogene_corrected_normed_gene_count.csv")
```


```{r get results}
treg_dds <- dds[,c(1:2, 5:6, 9:10)]
teff_dds <- dds[,c(3:4, 7:8, 11:12)]

treg_res <- results(treg_dds, contrast=c("condition", "S", "A")) %>% as.data.table(TRUE)
teff_res <- results(treg_dds, contrast=c("condition", "S", "A")) %>% as.data.table(TRUE)

# Treg_SATB1 vs Teff_SATB1
both_dds <- dds[, c(2,4,6,8,10,12)]
both_res <- results(satb1_dds, contrast=c("cell", "Treg", "Teff")) %>% as.data.table(TRUE)
```

```{r save DEGs}
limma_counts <- read.csv("../../data/novogene_corrected_normed_gene_count.csv")
limma_counts

treg_res_merged <- merge(treg_res, limma_counts, by.x="rn", by.y="X")
teff_res_merged <- merge(teff_res, limma_counts, by.x="rn", by.y="X")
both_res_merged <- merge(both_res, limma_counts, by.x="rn", by.y="X")

write.csv(treg_res_merged, "../../data/deg/Treg_S_vs_A.csv")
write.csv(teff_res_merged, "../../data/deg/Teff_S_vs_A.csv")
write.csv(both_res_merged, "../../data/deg/Treg_S_vs_Teff_S.csv")
```